<div class="product-block">
    <div class="product-block-title"><?= $block->escapeHtml($block->helper->getBlockTitle()) ?></div>
    <?php $product = $block->getProduct(); ?>
    <div class="product-block-image">
        <a href="<?= $product->getProductUrl() ?>"><img src="<?= $product->getImageUrl() ?>" alt="<?= $block->escapeHtml($product->getName()) ?>"></a>
    </div>
    <div class="product-block-info">
        <div class="product-block-name"><a href="<?= $product->getProductUrl() ?>"><?= $block->escapeHtml($product->getName()) ?></a></div>
        <div class="product-block-price"><?= $block->escapeHtml($product->getPrice()) ?></div>
        <div class="product-block-buy"><a href="<?= $block->escapeUrl($block->getBuyUrl()) ?>">Buy</a></div>
    </div>
</div>
